theme: jekyll-theme-leap-day
title: "Milkomeda: Safeguarding the Mobile GPU Interface Using WebGL Security Checks"
name: "Milkomeda: Safeguarding the Mobile GPU Interface Using WebGL Security Checks"
